- code/modules/tram/tram.dm
- code/modules/tram/tram_act.dm
- maps/testmap.dmm
- yonaguni.dme
Up for review. The tram code seems laggy in general, so optimizations are needed. I fixed a lot of issues with gibbing creating lag because the game was trying to gib the same thing multiple times, using a list, and implements basic collision behavior.
> Updates testing map with a tram and adds tram collision behavior

- code/ATMOSPHERICS/components/omni_devices/_omni_extras.dm
- code/ATMOSPHERICS/components/omni_devices/filter.dm
- code/ATMOSPHERICS/components/omni_devices/omni_base.dm
- code/ATMOSPHERICS/components/unary/vent_scrubber.dm
- code/game/machinery/alarm.dm
- code/game/objects/structures/inflatable.dm
- code/game/objects/structures/lattice.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/turf.dm
- code/modules/europa/turfs/ocean.dm
- code/modules/linda/linda_update.dm
- Omni filters can filter water
- Air alarms can set scrubbers to scrub water; scrubbers can scrub water
- Inflatables correctly block air/water
- `ChangeTurf()` calls `Destroy()` for ocean turf cleanup etc. Simulated wall `Destroy()` changed to not cause an infinite loop.
- `/obj/structure/Destroy()` and `/obj/effect/Destroy()` now wait until they're in nullspace to update atmos
> Fixes + improvements

- code/modules/admin/admin_verbs.dm
- code/modules/europa/mapgen/supplydrop.dm
- code/modules/random_map/building/building.dm
- code/modules/random_map/noise/ore.dm
- code/modules/random_map/random_map.dm
- code/modules/random_map/random_map_verbs.dm
- maps/testmap.dmm
- yonaguni.dme
https://dl.dropboxusercontent.com/u/16913760/bay/droppod.webm
> Added supply drops.

- code/controllers/emergency_shuttle_controller.dm
- code/controllers/shuttle_controller.dm
- code/global.dm
- code/modules/europa/hooks/ocean.dm
- code/modules/linda/linda_turf.dm
- code/modules/reagents/reagent_containers/food/condiment.dm
- code/modules/shuttles/shuttle_emergency.dm
- code/modules/xgm/xgm_gas_mixture.dm
The fucking thing flies through space anyway, the immersions can remain broken until we work out and code a proper lore-friendly replacement.
> Reverts escape shuttle changes.

- code/modules/tram/tram.dm
The tram code currently is a bit redundant and could be condensed down, but this for now fixes the issues and optimizes the trams (at least on the testmap, the trams on the europa map will probably need to be remapped to a simple box or something.)
> Tram fixes

- code/modules/ghosttrap/trap.dm
- code/modules/mob/living/carbon/brain/MMI.dm
Haven't tested this locally, will do it on the testing server with volunteers.
> Readded posibrain behavior.

- code/_helpers/maths.dm
- code/controllers/master_controller.dm
- code/game/turfs/turf.dm
- code/global.dm
- code/modules/europa/turfs/ocean.dm
- code/modules/linda/linda_turf.dm
- code/modules/multiz/turf.dm
- code/modules/random_map/_random_map_setup.dm
- code/modules/random_map/automata/automata.dm
- code/modules/random_map/automata/caves.dm
- code/modules/random_map/automata/diona.dm
- code/modules/random_map/building/building.dm
- code/modules/random_map/drop/droppod.dm
- code/modules/random_map/mazes/maze.dm
- code/modules/random_map/noise/noise.dm
- code/modules/random_map/noise/ore.dm
- code/modules/random_map/random_map.dm
I want to see if this changes anything on the main server re: map generation time.
> Optimizations.

- maps/europa-1.dmm
I'm an idiot, I will admit that
> Added the vents for the geothermal engines

- tools/GenerateChangelog/ss13_genchangelog.py
````
I'm sorry, I like making things PEP8 compliant, okay?
````
> ChangelogGen PEP8 compliance

- code/modules/europa/mobs/living/heavy_vehicle/components/_components.dm
- code/modules/europa/mobs/living/heavy_vehicle/components/arms.dm
- code/modules/europa/mobs/living/heavy_vehicle/components/body.dm
- code/modules/europa/mobs/living/heavy_vehicle/components/frame.dm
- code/modules/europa/mobs/living/heavy_vehicle/components/head.dm
- code/modules/europa/mobs/living/heavy_vehicle/components/legs.dm
- code/modules/europa/mobs/living/heavy_vehicle/mecha_construction.dm
- code/modules/multiz/turf_appearance.dm
Yonaguni#228
Yonaguni#227
Yonaguni#225
> Mech fixes.

- code/game/objects/random/random.dm
To aid in decorating maint, and decorating in general.
> Adds more random objects

- code/game/turfs/flooring/flooring_premade.dm
> Fixed broken floors being broken

- code/game/objects/random/random.dm
Adds random building materials to the random.dm. They come in stacks of 10. Currently their Icon is paper because I couldn't find where the steel icon was. When I, or someone else finally does, it can be changed.
**TO DO**
* Make plasteel rarer
* Change icon to steel
> Random Building Materials

- code/modules/client/preference_setup/global/03_language.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/new_player/preferences_setup.dm
Just keeping this up to date with my Bay fixes
> Tweaked a couple of fixes

- code/modules/clothing/head/hardhat.dm
- code/modules/projectiles/projectile.dm
- Adds hardhat action button
- Fixes projectile effect runtime
> Fixes from bay12

- code/modules/aspects/aspects_guns.dm
- code/modules/client/preference_setup/aspects/aspects.dm
- code/modules/guns/premade/premade_pistol.dm
Fixed Gunslinger weapon spawning.
Fixed aspect sanitization.
> Aspect tweaks.

- code/modules/surgery/generic.dm
- code/modules/surgery/implant.dm
- code/modules/surgery/organs_internal.dm
- code/modules/surgery/other.dm
Grossed up surgery with some real gross squelching sounds.
> Makes surgery more gross

- code/game/objects/random/random.dm
Changes it's icon to a chip bag to better indicate what it is as well.
> Adds more random junk to the random junk section.

- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
- code/modules/europa/psychics/psychic_item.dm
- code/modules/europa/psychics/psychic_mob.dm
- code/modules/mob/living/carbon/give.dm
- code/modules/mob/living/carbon/human/stripping.dm
- code/modules/recycling/disposal.dm
> Fixes #481

- code/modules/blob/blob.dm
- html/changelogs/zuhayr-redaction.yml
> Added a glow effect to blebs, thanks BlueNexus.

- code/modules/admin/admin_verbs.dm
- code/modules/mob/living/carbon/human/emote.dm
- maps/katydid/katydid_define.dm
> Added an admin verb for renaming the ship in case of griffons.

- code/game/jobs/job_controller.dm
- code/game/objects/items/devices/multitool.dm
> Couple of tweaks.

- code/modules/materials/materials.dm
- code/modules/power/fusion/core/core_field.dm
- code/modules/power/fusion/fusion_particle_catcher.dm
- code/modules/power/fusion/fusion_reactions.dm
- code/modules/xgm/xgm_gas_mixture.dm
> Further R-UST tweaks.

- code/modules/power/fusion/core/core_field.dm
> Stop getting disrupted by emitter beams!

- code/game/objects/items/devices/flashlight.dm
- code/game/objects/items/robot/robot_upgrades.dm
- code/game/objects/structures/barsign.dm
- code/modules/mob/living/silicon/robot/drone/drone.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/silicon/robot/robot.dm
> Lighting tweaks.

- tools/mapmerge/2clean_maps_aeolus.bat
- tools/mapmerge/2clean_maps_borderworld.bat
- tools/mapmerge/2clean_maps_katydid.bat
> Fixing an error in updated tools.

- baystation12.dme
- code/_helpers/global_lists.dm
- code/game/objects/items/weapons/grenades/chem_grenade.dm
- code/modules/admin/verbs/mapping.dm
- code/modules/hydroponics/spreading/spreading_growth.dm
- code/modules/hydroponics/trays/tray.dm
- code/modules/item_worth/reagents.dm
- code/modules/reagents/Chemistry-Debug.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
- code/modules/reagents/Chemistry-Recipes.dm
- code/modules/reagents/reagent_containers/spray.dm
The verb is very useful in keeping the wiki up to date.
Removed a couple of duplicated recipes and renamed Plant-B-Gone to generic weedkiller while I was at it.
> Added a chemistry debug verb for the wiki.

- code/game/turfs/space/space.dm
> Fixes runtime spam on space maps.

- code/modules/client/preference_setup/aspects/aspects.dm
- code/modules/europa/aspects/aspects.dm
- code/modules/europa/aspects/aspects_negative.dm
- code/modules/europa/aspects/aspects_psychic.dm
- code/modules/europa/aspects/aspects_traits.dm
- code/modules/europa/psychics/psychic_mob.dm
- code/modules/mob/transform_procs.dm
> Fixes a bug with AIs getting psi powers.

- html/changelogs/zuhayr-surgery.yml
> Changelog for surgery changes.

- code/modules/surgery/bones.dm
- maps/aeolus/aeolus_define.dm
- maps/borderworld/borderworld_define.dm
- maps/europa/europa_define.dm
- maps/katydid/katydid_define.dm
- maps/~mapsystem/maps.dm
> Added lore blurbs to the maps.

- code/ZAS/Connection.dm
- code/ZAS/Controller.dm
- code/game/atoms.dm
- code/game/turfs/natural/ocean.dm
- code/modules/mob/living/life.dm
- maps/europa/europa_define.dm
Good news is, which this in place, the water map is now unbugged and only needs a finished map to be playable.
> Reverts some ZAS changes, adds a return_environment() proc.

- code/__defines/aspects.dm
- code/game/objects/items/weapons/storage/toolbox.dm
- code/game/objects/items/weapons/tape.dm
- code/modules/europa/aspects/aspects_background.dm
Spawns you with a loaded toolbox.
Also a tiny nerf to duct tape size.
> Adds handyman aspect.

- code/game/jobs/job/silicon.dm
> Commented out the AI job due to client performance issues.

- baystation12.dme
- code/game/base_turf.dm
- code/game/jobs/job/job.dm
- code/game/jobs/job_controller.dm
- code/modules/admin/admin_verbs.dm
- code/modules/random_map/noise/seafloor.dm
- maps/europa/europa_define.dm
- maps/~mapsystem/maps.dm
> Added a replace-space mapgen for the ocean level.

- code/modules/europa/planar_lighting/light_effect.dm
- code/modules/europa/planar_lighting/light_effect_cast.dm
> Removed shadow casting appearance churn

- baystation12.dme
- code/datums/supplypacks/engineering.dm
- code/modules/materials/material_sheets.dm
> Added various material sheets to cargo.

- code/modules/europa/guns/ammo/ammo_casing.dm
> Ammunition matter fix.

- maps/~mapsystem/maps.dm
> Fixes up a few issues with the submerge-map verb.

- code/ATMOSPHERICS/pipes.dm
- code/modules/europa/fluids/fluid_water_act.dm
> Should prevent vents and such being damaged by water.

- code/modules/europa/fluids/fluid_water_act.dm
> I'm an idiot.

- code/datums/uplink/grenades.dm
- code/game/gamemodes/game_mode.dm
- code/game/machinery/lathes/designs/designs_circuits.dm
- code/modules/events/ion_storm.dm
- code/modules/materials/materials.dm
- code/modules/power/fusion/fuel_assembly/fuel_assembly.dm
- code/modules/power/fusion/fuel_assembly/fuel_compressor.dm
- code/modules/power/fusion/fusion_reactions.dm
- code/modules/power/singularity/singularity.dm
> Removed some references to supermatter due to lore.

- code/modules/europa/planar_lighting/light_atom_set.dm
- code/modules/europa/planar_lighting/light_effect.dm
- code/modules/power/lighting.dm
Runtime prevention in Destroy()
Faster light off proc
Hopefully resolves #553
> Lighting efficiency updates

- code/game/machinery/telecomms/broadcaster.dm
> Fixes a null loc runtime in telecomms.

- code/game/jobs/job_controller.dm
- code/game/machinery/doors/blast_door.dm
- code/game/objects/structures/watercloset.dm
- code/modules/modular_computers/file_system/programs/card.dm
- nano/templates/identification_computer.tmpl
> Runtime fixes.

- scripts/server.sh
Sick of updating this every time. :U
> Updated script to fit current env.

- code/modules/mob/living/silicon/robot/drone/drone_remote_control.dm
- code/modules/mob/observer/freelook/chunk.dm
- code/modules/power/lighting.dm
- maps/katydid/katydid_jobs.dm
- maps/yonaguni/yonaguni_jobs.dm
> Fixed issues with AI crashing, reenabled AI.

- code/ATMOSPHERICS/components/unary/vent_scrubber.dm
- code/ZAS/Fire.dm
- code/__defines/atmos.dm
- code/defines/gases.dm
- code/game/machinery/atmoalter/canister.dm
- code/game/machinery/atmoalter/scrubber.dm
- code/game/objects/items/weapons/manuals.dm
- code/game/turfs/flooring/flooring_premade.dm
- code/modules/power/fusion/core/core_control.dm
- code/modules/power/fusion/core/core_field.dm
- code/modules/power/fusion/fuel_assembly/fuel_assembly.dm
- code/modules/power/fusion/fuel_assembly/fuel_compressor.dm
- code/modules/power/fusion/fusion_reactions.dm
- code/modules/xgm/xgm_gas_data.dm
> RUST tweaks

- maps/yonaguni/yonaguni_define.dm
> Removed testing verbs.

- code/datums/uplink/hardsuit_modules.dm
- code/game/machinery/alarm.dm
- code/game/machinery/computer/computer.dm
- code/game/machinery/requests_console.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/devices/uplink_random_lists.dm
- code/modules/clothing/spacesuits/rig/modules/combat.dm
- code/modules/clothing/spacesuits/rig/suits/light.dm
- code/modules/clothing/spacesuits/rig/suits/merc.dm
- code/modules/item_worth/worths_list.dm
- code/modules/power/apc.dm
> Fixing some light effects on machines.

- code/game/machinery/kitchen/cooking_machines/_cooker.dm
- maps/yonaguni/yonaguni_areas.dm
> Couple of minor tweaks.

- code/controllers/subsystems/plants.dm
Fixes a bug where plants would process forever, ticking as fast as the MC would allow, potentially causing lag.
> Fix plant processing

- code/game/gamemodes/cult/cult.dm
Bugs out the ass, literally unplayable.
> Disabled cult.

- code/game/turfs/natural/ocean.dm
- code/game/turfs/simulated.dm
- code/game/turfs/turf.dm
- code/modules/power/port_gen.dm
> Fixes mk 2

- code/controllers/evacuation/evacuation.dm
- code/controllers/evacuation/evacuation_pods.dm
- code/controllers/evacuation/evacuation_shuttle.dm
- code/game/jobs/job_controller.dm
- code/game/machinery/status_display.dm
- code/game/machinery/status_display_ai.dm
- code/modules/europa/planar_lighting/light_effect_cast.dm
- code/modules/shuttles/shuttle_emergency.dm
- maps/yonaguni/yonaguni_areas.dm
- maps/yonaguni/yonaguni_define.dm
- maps/~mapsystem/maps.dm
> Fixes mk 4

- code/game/atoms_movable.dm
- code/game/objects/effects/decals/posters/bs12.dm
- code/game/objects/items/robot/robot_parts.dm
- code/game/objects/structures/pit.dm
- code/global.dm
- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/europa/mechs/components/_components.dm
- code/modules/europa/mechs/equipment/_equipment.dm
- code/modules/europa/mechs/mecha_construction.dm
- code/modules/europa/mechs/mecha_icon.dm
- code/modules/europa/mechs/mecha_interaction.dm
- code/modules/games/spaceball_cards.dm
- code/modules/mob/mob_movement.dm
- code/modules/organs/internal/heart.dm
- code/modules/vehicles/bike.dm
> Fixes mk 7

- code/datums/helper_datums/teleport.dm
- code/game/gamemodes/endgame/supermatter_cascade/blob.dm
- code/game/gamemodes/endgame/supermatter_cascade/portal.dm
- code/game/gamemodes/endgame/supermatter_cascade/universe.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/heist/heist.dm
- code/game/machinery/Beacon.dm
- code/game/machinery/bluespacerelay.dm
- code/game/machinery/lathes/designs/designs_circuits.dm
- code/game/machinery/teleporter.dm
- code/game/objects/effects/overlays.dm
- code/game/objects/items/weapons/storage/backpack.dm
- code/game/turfs/space/space.dm
- code/game/turfs/unsimulated/floor.dm
- code/modules/admin/topic.dm
- code/modules/awaymissions/bluespaceartillery.dm
- code/modules/hydroponics/seed_datums.dm
- code/modules/mob/living/carbon/metroid/items.dm
- code/modules/modular_computers/file_system/programs/comm.dm
- code/modules/power/cell.dm
- code/modules/reagents/reagent_containers/glass.dm
- code/modules/shuttles/landmarks.dm
- code/modules/shuttles/shuttle_emergency.dm
> Bluespace pls go.

- chinsky - landmark.yml
I don't think this is supposed to be here.
> Remove odd file in root

- code/game/turfs/flooring/flooring_decals.dm
- code/modules/mob/mob_movement.dm
> Aurora-Europa multiz fixes.

- code/modules/admin/secrets/random_events/gravity.dm
- code/modules/events/event_container.dm
- maps/katydid/katydid_define.dm
- maps/~mapsystem/maps.dm
> Added a map level var for the gravity failure event.

- code/controllers/subsystems/tgui.dm
- code/modules/organs/blood.dm
- code/modules/reagents/reagent_containers/syringes.dm
Why does this fix the problem
What the fuck BYOND
Fixes #612
> Blood fix.

- code/modules/organs/blood.dm
- code/modules/reagents/Chemistry-Reagents.dm
> Should fix blood not transferring properly.

- code/modules/europa/fluids/fluid_drowning.dm
> Fixes a runtime in breathing code.

- code/game/objects/items/devices/uplink.dm
- code/modules/europa/guns/ammo/ammo_casing.dm
- code/modules/europa/psychics/psychic_power.dm
> Fixed a runtime in uplink code.

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/mob.dm
> Stole Look Up verb from Bay.

- .travis.yml
Planning on removing tgui anyway down the track and currently a bug that I have no idea how to fix is breaking travis builds.
> Removed gulp/tgui checks from Travis.

- .travis.yml
> Further refining Travis tgui removal.

- code/modules/planar_lighting/light_effect_cast.dm
> Some lighting optimization from Lohikar, thanks Lohi.

- code/game/antagonist/station/traitor.dm
- code/modules/psychics/complexus/complexus.dm
- code/modules/psychics/complexus/complexus_process.dm
- code/modules/psychics/equipment/psipower_tk.dm
- code/modules/psychics/faculties/psychokinesis.dm
> Fixes a runtime and uplink spawning.

- code/modules/organs/organ_icon.dm
> Fixed a small problem with limbs spawned on observer join.

- code/modules/shuttles/landmarks.dm
> Fixes a shuttle landmark issue.

- code/ATMOSPHERICS/components/omni_devices/filter.dm
- code/_helpers/functional.dm
- code/modules/mob/living/simple_animal/constructs/soulstone.dm
- code/modules/overmap/events/event.dm
Replaces some uses of 'filters' & removes a rogue period preventing compile on 512.
> Fix compile on 512

- code/modules/mob/new_player/new_player.dm
- maps/yonaguni/yonaguni_jobs.dm
Merged the previous one early, whoops.
> Job info again.

- code/game/objects/structures/watercloset.dm
- code/modules/events/event_container.dm
- code/modules/organs/blood.dm
- code/modules/psychics/complexus/complexus_process.dm
- code/modules/psychics/mob/mob.dm
- code/modules/psychics/mob/mob_telepathy.dm
- code/modules/terminals/term_program.dm
> Various fixes.

- code/__defines/species_languages.dm
- code/modules/mob/language/generic.dm
As far as I can tell all the code is there and has been there for awhile, just didn't have a datum to use it.
> Made sign language available.

- code/modules/client/preferences.dm
- maps/yonaguni/yonaguni_jobs.dm
> Fixes prosthetic/amputation aspect sorting woes.

- code/modules/aspects/aspects_guns.dm
- code/modules/mob/new_player/sprite_accessories.dm
NO MORE BALD.
DNM, checking that it really does fix bald.
> Fixes bald.

- code/modules/mob/language/factional.dm
- code/stylesheet.dm
They now have colours, syllables and verbs!
> Adds syllables and colours to the Languages

- code/__defines/subsystem-priority.dm
- code/controllers/subsystems/environment.dm
- code/controllers/subsystems/event.dm
- europa.dme
- maps/testing/testing_define.dm
- maps/~mapsystem/maps.dm
Colours are arse but whatever, system works.
> Added an extremely simple day/night cycle and associated subsystem.

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .gitignore
- COPYING
- README.md
- code/game/world.dm
- code/modules/mob/new_player/login.dm
- html/templates/header.html
- scripts/server.sh
- tools/dmitool/merging.txt
This is a priority one so I'm probably going to merge it myself as soon as Travis passes.
> Updating numerous mentions of Baystation 12 and their resources.

- code/modules/mob/skills/skill.dm
I'm sure we'll end up tweaking/changing the system as necessary, this is just to unlock all skills as a possibility for general testing/dev purposes if nothing else.
> Sets max skill default for all skills to max
