Yonaguni/EuropaStation

code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/silicon/ai/icons.dm

Both malfunctioning and VIP AIs now have special sets of displays to pick from.
The VIP set is more of a placeholder than anything. I tried to make a gold version of the default AI display but I was too scrub.

AI Display selection now supports VIP-only sets.

---

code/modules/multiz/turf.dm

Turns out there was a race condition in the dev merge that only occurred if you joined during the initial startup time of the server.  Zuhayr fixed that in #206, but that also nuked some unrelated code.  I'm not going to even try to fix the turf_initializer stuff as it's weird.

Fix for open space.

---

code/__defines/atmos.dm
code/game/objects/items/weapons/job_items/tape_rolls.dm
code/modules/europa/clothing/helmet.dm

- Fixes #280 
Due to Linda being "lazy" it needs a lower suspend ratio, otherwise it stops before the room is properly depressurized, resulting in 5kPa differences between turfs next to each other. This meant unless an air alarm was on top of an air scrubber it would never be able to finish a siphon cycle.
Also fixed mapped in engineering tape being rendered under airlocks.
- Fixes #197 
There are likely to be more missing hide tags on items, but I'm not personally going to test every single item.

Various fixes

---

code/modules/clothing/clothing.dm

Fixes a bad index runtime when helmets have no sprite_sheets list.

Helmet overlay runtime fix

---

code/__defines/europa.dm

Just a couple of defines for working with the ocean depth. 
Useful for setting things like airlock target pressure.

Ocean depth defines

---

code/__defines/damage_organs.dm
code/game/objects/items/stacks/medical.dm
code/modules/organs/organ_external.dm
code/modules/organs/wound.dm
code/modules/projectiles/projectile/bullets.dm
code/modules/surgery/suture_wounds.dm

Adds new type of wounds - piercing.
Those are caused by sharp things without the edge, namely bullets.
Unlike other wounds, they do not merge together, so if you empty .38 in a guy, he'll have 6 .38 holes instead of one megawound. Get a shotgun if you want one.
Touched code all over the place to make stuff recognize new type.
Added new var for wounds - open, since damtype checks were getting wordy.
Cleaned up bleeding() proc a bit with power of OOP.

Piercing wounds

---

code/modules/guns/components/chambers/chamber.dm
code/modules/guns/components/component.dm
code/modules/guns/gun_assembly.dm
code/modules/guns/gun_composite.dm

They are now broken in new way - overlayed over darkness or something, and also cause white square? appear over intent picker.
Oh well.
Also axes bunch of commented out / unused code.
Moves ammo overlay to overlay of chambers, cause guns now use parts themselves as overlays.

Fixes gun icons on newlighting.

---

code/modules/mob/living/carbon/human/human_tail.dm

Stops the tail segments from getting out of time with the parent mob.
There's still some separation when going around corners, but at least this stops the "wobble effect" when moving in a straight line.

Fixed snake tail movement

---

code/modules/planar_lighting/light_effect_cast.dm

Here's a pretty significant optimization for europa lights. You may or may not be aware of 'appearance churn', it's a similar problem to long string concatenation loops.
Your system of adding to overlays one by one means you create a new appearance after each overlay addition, as well as byond internally looping through apeparances to remove your old appearance.
This system creates the final appearance with a single appearance build.
This removes about 50% of the cost of europa lights, approximately.

Optimization for Europa Lights

---

baystation12.dme
code/controllers/configuration.dm
code/global.dm
code/modules/client/client defines.dm
code/modules/mob/new_player/login.dm
code/modules/mob/new_player/server_info_window.dm
config/example/config.txt
config/example/motd.txt
config/example/rules.html
maps/~mapsystem/maps.dm

This window must be closed to continue to the normal menu, and basically consists of the MOTD + Rules + Map info + some useful links. Various config changes etc. made as a result, examples should be provided. Doesn't include actual configs or MOTD I tested with. When/if this goes through I'll throw them Zuh's way or whatever.
A global list (ew I know) is used to check which ckeys have pressed the button so you only see it once per round. It's also available as a Server Information verb in the OOC tab.
The idea behind this is that it can be used to show current info, event info, map-specific info, or whatever, as well as preventing "I didn't read the rules" as an excuse because you literally have to click a button on a page showing you the rules to continue.

Adds a new Server Info window

---

code/modules/random_map/random_map.dm

Replacing this seems to fix unit testing on Linux for the Katydid. Might affect map loading speed/lag as well.

Maybe fix Katydid unit testing

---

code/world.dm

Meant to delete this in #579, musta forgot.
This is set by the MC now so that subsystems can still initialize even if there's no players. (master.dm:181)

Fix world.sleep_offline being set too early

---

code/controllers/master/admin.dm
code/modules/mob/mob.dm

Uncomments/fixes subsystem watching - clients with holders can shift-click on subsystems in the MC panel to add them to the Status panel so individual subsystems can be monitored without having to have the extremely laggy MC panel open.

Fix/implement shift-click SS monitoring

---

code/controllers/voting.dm
code/modules/shuttles/shuttle_autodock.dm
code/modules/shuttles/shuttle_emergency.dm
code/modules/shuttles/shuttle_ferry.dm
code/modules/shuttles/shuttles_multi.dm
maps/yonaguni/yonaguni_events.dm
maps/~mapsystem/maps.dm

Fixes mk 8

---

code/game/machinery/lathes/autolathe.dm
code/game/machinery/lathes/autolathe_types.dm
code/game/machinery/lathes/designs/designs.dm
code/game/machinery/lathes/designs/designs_ammo.dm
code/game/machinery/lathes/designs/designs_circuits.dm
code/game/machinery/lathes/designs/designs_heavy.dm
code/game/machinery/lathes/designs/designs_robotics.dm
code/modules/europa/guns/ammo/ammo_magazine.dm
code/modules/europa/terminals/term_program_lathe.dm

- Fabricators can now print out arbitrary multiples instead of only sheets.
- Max multiple for fabs is now 20.
- Ammunition can be printed en masse.
- Fabrication times tweaked.
- Regular lathe can now print all appropriate empty magazines.
- Magazines set their caliber from expected contents even in the absence of initial ammo.

Ammo fabricator changes.

---

code/controllers/subsystems/openturf.dm

`no_mutate` openturfs mimicing opaque turfs could unintentionally become opaque themselves.

Fix a minor openspace bug

---

code/modules/reagents/Chemistry-Machinery.dm

PR stolen from [here.](https://github.com/Baystation12/Baystation12/pull/20280)
This fixes a terrible bug that can crash dream daemon without any hassle.

Fix infinite while loop in chemistry

---

code/game/turfs/simulated/wall_icon.dm

Accidentally introduced in Baystation12/Baystation12#24112 ?
Damage overlays would never be populated because it's already an empty 16 length array.

Fixes damage overlays

---

code/modules/multiz/structures.dm
code/unit_tests/map_tests.dm

Removes the requirement for ladders to be on open space to correctly link with the ladders below, and stops them adding lattice to the tile they're on. Ladder pairs should now function on any terrain they're placed on.
This allows ladders to be used between 2 Z-levels that have no open space and no default base turfs of open space, so you can have Z-levels which are ladder-traversable whilst still being further apart than just sat on top of each other.
Third time's the fuckin' charm right?

Removes some ladder requirements

---

code/__defines/misc.dm
code/modules/client/preferences.dm
code/modules/mob/new_player/login.dm
code/modules/mob/new_player/new_player.dm

Removes 1 call to show the new player panel which I'm certain is defunct and should not be occurring (on pref setup), to prevent the panel appearing when the player still has the server info window open.
Forcibly closes the new player panel when the client logs in, to ensure that it cannot be open (it would remain open if it already was and the player was connected over the server restart, at which point it would break).
Adds a global definition of the player panel window ID so that we're sure we're creating and closing the same window ID.
Suggestions of other ways to do this very welcome.

Makes the info window/new player panel a bit more robust

---

code/__defines/_planes+layers.dm
code/game/turfs/flooring/flooring_decals.dm
code/game/turfs/simulated/floor.dm
code/game/turfs/simulated/floor_icon.dm
code/game/turfs/turf_ao.dm
code/game/turfs/turf_changing.dm

AO was overwriting decals because they don't use SSOverlay, and they would then overwrite AO overlays because they don't have a plane/layer.
This adds those, so decals will now correctly render and AO will render on top of them (and various other things).
Before - No decals next to wall where there's AO:
After - AO on top of decals.

Updates decals to fix issues with AO

---

code/modules/power/lighting.dm

Updates tubes (and the default no-sprite tube) to LIGHT_COLOR_HALOGEN and the bulb to LIGHT_COLOR_TUNGSTEN. The halogen tubes have a cooler feel than current, and the bulbs are slightly warmer, giving a different feel and some enhanced contrast.

Updates lights to LIGHT_COLOR_HALOGEN and LIGHT_COLOR_TUNGSTEN
